[package]
name = "browser_engine"
version = "0.1.0"
authors = ["Sidharth K <sidharth.k9@mailbox.org>"]
edition = "2018"


[dependencies]
gfx = "0.18.0"
gfx_text = "0.27.0"
gfx_window_glutin = "0.31.0"
glutin = "0.26.0"